version: 0.2

phases:
  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $REPOSITORY_URI:latest -f /tmp/cp-action-source/src/Dockerfile /tmp/cp-action-source
      - docker push $REPOSITORY_URI:latest
artifacts:
  files:
    - '**/*'
